### PR TITLE
Characteristic change callback instead of event listener

### PR DESCRIPTION
**Pull request by aileo**
Related to #63, trying to not miss any message by keeping event listener and changing callback.

### CODE REVIEW

**Comment by nathankellenicki** [comment]
I'm unable to test this right now (I fly back home tonight) but I suspect this might cause a few problems. Normally LPF2 hubs don't start sending data until there's a subscriber to the characteristic asking for notifications, so subscribing that early may cause data to be sent before we're ready for it.

Also in the case of WeDo 2.0 hubs, there are a lot more charactistics on there that we care about, so subscribing to all of them indiscriminately could cause a lot more chatter and therefore BLE latency.

**Comment by aileo** [comment]
It should not start sending as it does not call startNotification, it only add the listener.

**Comment by nathankellenicki** [comment]
> It should not start sending as it does not call startNotification, it only add the listener.

@aileo I see, sorry I missed that.

I think I'm still missing something though. So now there's a persistent listener on the characteristic event, which does the conversion, and eventually calls the call back on `_listeners`. However, if there's nothing on `_listeners`, the message will get lost anyway? What problem is this solving?

Sorry if I'm misunderstanding the code/purpose. :)

**Comment by aileo** [comment]
It "solve" the problem, that we suspect does not exist: removing and adding the listener.

This instead change the function called in the listener so it guarantee:
- no message can be lost due to no listener 
- a message can't be read twice as there is not two listeners at the same time (even during the same tick).

**Comment by nathankellenicki** [comment]
> This instead change the function called in the listener so it guarantee:
> 
> * no message can be lost due to no listener

How does it solve this problem? There is always a listener yes, but that listener calls a callback with the message. If there is no callback, it doesn't do anything with the message, losing it. If we want to take this approach, should we put the message into the mailbox to be redelivered when a new callback is added?

It seems this is just moving the same problem a little further down the tree...

**Comment by nathankellenicki** [comment]
> * a message can't be read twice as there is not two listeners at the same time (even during the same tick).

I can see it solves this edge case. We could accept this PR as a fix for this, and think some more about lost messages?

**Comment by aileo** [comment]
Sorry, my intent was not clear, it is only meant to prevent message drop from the event listener change as I mentionned in [#63](https://github.com/nathankellenicki/node-poweredup/issues/63#issuecomment-565595879):

> [...] And the old event listener is removed before the new one is added but I doubt it would lead to miss a message.


> We could accept this PR as a fix for this, and think some more about lost messages?

I think we should not, it seems it could cause more problems than it solves

> should we put the message into the mailbox to be redelivered when a new callback is added

I will take this approach, do you think this part should handle the multiple frame messages ?

**Comment by nathankellenicki** [comment]
> I will take this approach, do you think this part should handle the multiple frame messages ?

Thanks for the help. :) I think it's needed yep. I have seen it happen where multiple frames appear in the same payload. I was also thinking - there is the case where a single message frame can be split across multiple payloads depending on MTU, so I think the case needs to be handled where a callback gets added in the middle of a full frame arriving (ie. stashing a partial message in the mailbox and redelivered later)

Worth noting that all of these cases are handled in the more advanced message parsing inside lpf2hub.ts, but I simplified it in the WebBLE discovery - but obviously forgot to handle these edge cases.

**Comment by aileo** [comment]
This is totally outdated, better start from the current version again.

**Pull request closed without merging**
